language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: jp9Ex8VvlmVmch6Qrv3/D/F2ITW+XhRoR1XwPYVuZ+JgfXHAooi9XtMZzFMVN3C6Dy9mVuVe5e3FsBApYAS/tzEjLxIoZWZ3/FHNlwgaNhQguaSOY/KCPVWXLiAenOTlO2UEeeqOuNZKm7Zll1CfadO2VbncSDKoEDFXOPayUAk=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: UVtdq9KNR5gKtIVqRH7sD9rHsI9VVdIzJvjUbnIK6vYcU/GjpynBCW/5k4c3ue3mw7SbGoCg41dQZmS+MvPF4gX6IV+hFrOxc2NtFVS6aGiBoxjnanC4wqKjGH5iMq11vnK4eoAf9+77DhaDqFEFXYlwIXxoFmUDO0ltroZrBQ4=
sudo: false
